### ISSUE TITLE
build failed on CentOS 6.6 x86_64

### ISSUE THREAD

**Issue by zhuyie** [airtrack/stunnel#1]
cat /etc/redhat-release
CentOS release 6.6 (Final)

rustc --version
rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)

cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustc-serialize v0.3.13
 Downloading rand v0.3.8
 Downloading time v0.1.25
 Downloading rust-crypto v0.2.31
 Downloading libc v0.1.6
 Downloading gcc v0.3.4
   Compiling gcc v0.3.4
   Compiling libc v0.1.6
   Compiling rustc-serialize v0.3.13
   Compiling time v0.1.25
   Compiling rust-crypto v0.2.31
   Compiling rand v0.3.8
   Compiling stunnel v0.0.1 (file:///home/zhuyie/code/stunnel)
src/lib.rs:27:31: 27:32 error: expected one of `(`, `+`, `::`, `;`, `<`, or `]`, found `,`
src/lib.rs:27     pub const VERIFY_DATA: [u8, ..8] =
                                                                       ^
Could not compile `stunnel`.

To learn more, run the command again with --verbose.

**Comment by airtrack** [comment]
Please pull the new version, and use nightly-build compiler to build it, because it depends on several unstable functions, e.g. `lookup_host`.
