### ISSUE TITLE
如何修改本地客户端监听的端口号？

### ISSUE THREAD

**Issue by luckypoem** [airtrack/stunnel#2]
hi。
我修改了本地机器里的~/stunnel-by-airtrack/src/bin/client.rs文件的第143行里的1080为其他端口，比如2080.也修改了linux vps上的~/stunnel-by-airtrack/src/bin/client.rs文件的第143行里的1080为其他端口，比如2080。但是在客户机器（mac)上运行nohup ./client server_ip:7288 mykey 1 > /dev/null &后，设置浏览器的socks5代理为127.0.0.1:2080，翻墙失败。设为127.0.0.1:1080，则翻墙成功。这说明修改根本没生效，
为什么呢？

**Comment by airtrack** [comment]
Mac OS X 下 `netstat -anp tcp | grep client` 看看实际绑定的端口，端口 `1080` 是 `SOCKS 5` 的具名端口，只在客户端上默认绑定，你如果需要改端口的话，确实是在你指出的那行代码里改。
