### ISSUE TITLE
能否实现icmp协议的隧道。

### ISSUE THREAD

**Issue by YDHCUI** [airtrack/stunnel#8]
校园网里面晚上经常会断网，但是我看ip是可以ping通的。所以想要一个icmp协议的tunnel。
另外我看kcp是纯算法协议 应该支持使用icmp的。

**Comment by airtrack** [comment]
没有这个规划和打算，以前了解过伪装 ICMP 的逻辑，这种方式并没有普适性，速度也会比 UDP 的差很多。

实际使用可以试试监听 TCP 80 端口。
